version: '3.9'
services:
  jupyter_health:
    container_name: ${CONTAINER_PREFIX}_jupyter_health
    image: healthcare_team
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8888:8888
    networks:
      - app-network
    command:
      - "jupyter"
      - "lab"
      - "--ip=0.0.0.0"
      - "--port=8888"
      - "--no-browser"
      - "--allow-root"
      - "--NotebookApp.token=''"
      - "--NotebookApp.notebook_dir='/app'"      
networks:
  app-network:
    driver: bridge
